"""FastAPI application entrypoint: creates the app, wires up CORS, and
mounts the versioned API router. OpenAPI docs are auto-generated by FastAPI
at /docs, which is the API contract stock-platform's own frontend builds
against."""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.v1.router import api_router
from app.core.config import get_settings

settings = get_settings()

app = FastAPI(title=settings.PROJECT_NAME, version="0.1.0")

# Split the comma-separated CORS_ORIGINS env var into a list; "*" (the
# default) allows any origin, which is fine for local dev but should be
# restricted to the real frontend origin in deployed environments.
origins = [o.strip() for o in settings.CORS_ORIGINS.split(",")] if settings.CORS_ORIGINS != "*" else ["*"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router, prefix=settings.API_V1_PREFIX)


@app.get("/healthz", tags=["meta"])
def healthz() -> dict[str, str]:
    """Basic liveness check for container orchestration (k8s probes etc.)
    and for the frontend's own boot-time connectivity check — deliberately
    does not touch the DB so it stays cheap and fast."""
    return {"status": "ok"}
